global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'billing-service'
    static_configs:
      - targets: ['host.docker.internal:8085']
    metrics_path: '/actuator/prometheus'